### ISSUE TITLE
3x3 and 5x5 Gaussian kernel sizes?

### ISSUE THREAD

**Issue by bfreskura** [cszn/BSRGAN#15]
Hi @cszn,

Great work on the paper, the results are really fascinating.

Is there any reason why you haven't included 3x3 and 5x5 Gaussian blur kernels? They seem to be pretty standard so I was wondering why they aren't included. 

My line of reasoning is that including them could expand the augmentation space and thus help with generalization.

**Comment by cszn** [comment]
3x3 and 5x5 are special cases of 7x7, 9x9, ...
So, I do not think there would be any big difference.
