### ISSUE TITLE
大佬，求教 训练代码

### ISSUE THREAD

**Issue by tongchangD** [cszn/BSRGAN#19]
大佬，请问啥时候才会看源训练代码，感觉测试效果非常棒。

**Comment by tongchangD** [comment]
好想做个伸手党，[想哭]，[想笑],[哭笑不得]

**Comment by tongchangD** [comment]
找到一份代码 来自 一位 韩国选手 
https://github.com/HeaseoChung/BSRGAN-PyTorch

**Comment by jeejeeli** [comment]
[Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN ) 更香

**Comment by tongchangD** [comment]
> [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) 更香

何处此言，和 腾讯的 RealSR 比 哪个更香

**Comment by tongchangD** [comment]
> [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) 更香

你说的论文只是贴了一些超分效果比较好的图片,不知道他在开源数据集上测试效果怎么样

**Comment by cszn** [comment]
I have released the [extended BSRGAN degradation model](https://github.com/cszn/BSRGAN/blob/f08c9fccad11bbe7669eb355a5f10ddf6aaff585/utils/utils_blindsr.py#L432) and I will update the training code in [KAIR](https://github.com/cszn/KAIR).

**Comment by tongchangD** [comment]
thanks， 我觉得之前这个 韩国选手复现的[代码](https://github.com/HeaseoChung/BSRGAN-PyTorch)
不是很对，尤其是参数模块
