### ISSUE TITLE
训练参数iter设置问题

### ISSUE THREAD

**Issue by sunyclj** [cszn/BSRGAN#30]
请问您训练的x2超分模型硬件算力是怎样的？iter为多少停止训练？

**Comment by lucky-zwx** [comment]
> 请问您训练的x2超分模型硬件算力是怎样的？iter为多少停止训练？
请问有结果么？

**Comment by sunyclj** [comment]
@lucky-zwx 公开数据集和自己的数据训练的，3块rtx6000，训练时长约15天，根据指标停止训练的；超分效果不错，但是2k无法实时；

**Comment by lucky-zwx** [comment]
请问是psnr加GAN的训练时长么？

**Comment by lucky-zwx** [comment]
> @lucky-zwx 公开数据集和自己的数据训练的，3块rtx6000，训练时长约15天，根据指标停止训练的；超分效果不错，但是2k无法实时；

不需要将1000000个epoch全部跑完？

**Comment by sunyclj** [comment]
@lucky-zwx 是psnr和gan的时间，我是优化之后训练的；不需要跑完设置的epoch，看指标收敛就可以了；

**Comment by lucky-zwx** [comment]
> > @lucky-zwx 公开数据集和自己的数据训练的，3块rtx6000，训练时长约15天，根据指标停止训练的；超分效果不错，但是2k无法实时；
> 
> 不需要将1000000个epoch全部跑完？

呃，再问一下训练指标大概到多少可以停止训练了？

**Comment by sunyclj** [comment]
@lucky-zwx 测试多个模型，指标趋于收敛就可以停止训练；在DIV2K_val数据集上，最佳psnr指标为30.8622
