### ISSUE TITLE
Possible bug in degradation_bsrgan

### ISSUE THREAD

**Issue by DanilKonon** [cszn/BSRGAN#33]
It is possible that dimensions are permutated in the cropping operation in `degradation_bsrgan_plus`, `degradation_bsrgan` functions in [541](https://github.com/cszn/BSRGAN/blob/main/utils/utils_blindsr.py#L541),  [450](https://github.com/cszn/BSRGAN/blob/main/utils/utils_blindsr.py#L450) lines. 

It should be 
` img = img.copy()[:h1 - h1 % sf, :w1 - w1 % sf, ...]  # mod crop`
instead of
` img = img.copy()[:w1 - w1 % sf, :h1 - h1 % sf, ...]  # mod crop`

**Comment by XiaoqiangZhou** [comment]
I have the same problem.

**Comment by junseokoh1** [comment]
I think this is bug. I also change the code to degradation model

**Comment by cszn** [comment]
Thanks. Fixed.
