### ISSUE TITLE
What does 'axis length' mean?

### ISSUE THREAD

**Issue by AlanZhang1995** [cszn/BSRGAN#4]
As section 3.1 of your paper said, the length of each axis for scale factors 2 and 4 uniformly from [0.5, 6] and [0.5, 8], respectively. However, I am not sure what does that mean. In my understanding, gaussian kernel needs only 1. kernel size, 2. eigen-vals, and 3. rotation angle.

I will appreciate it if you can reply at any time you are available.
Thank you!

**Comment by AlanZhang1995** [comment]
Another question is about the remedy of nearest downsampling. As described in the paper, an **isotropic** Gaussian kernel is used. However, its kernel width is set to that of $B_{aniso}$. I wonder whether it is a typo.

**Comment by cszn** [comment]
Some related codes can be found in [SRMD](https://github.com/cszn/SRMD), [USRNet](https://github.com/cszn/USRNet) and [KAIR](https://github.com/cszn/KAIR).

**Comment by AlanZhang1995** [comment]
> KAIR

Thanks a lot for your reply!

I find some related codes these days, for example:
https://github.com/cszn/SRMD/blob/master/TrainingCodes/kernels/anisotropic_Gaussian.m
https://github.com/cszn/USRNet/blob/4fb56deb80d655abb722ff83750ad3df163ef833/utils/utils_sisr.py#L129
https://github.com/cszn/KAIR/blob/5beaf297be34c701d33aca2890879347b8155c7c/utils/utils_sisr.py#L172

However, I have not found an answer yet. I suppose ‘kernel width’ in your paper corresponds to lambda in these codes, but what ‘axis length’ corresponds to?

**Comment by cszn** [comment]
The length of axis has the same meaning as scaling of eigenvalues, see [KernelGAN](https://arxiv.org/abs/1909.06581) and [SRMD](https://openaccess.thecvf.com/content_cvpr_2018/papers/Zhang_Learning_a_Single_CVPR_2018_paper.pdf). $B_{aniso}$ should be $B_{iso}$. For the kernel width, please refer to the paper entitled "Revisiting Single Image Super-Resolution Under Internet Environment: Blur Kernels and Reconstruction Algorithms".
