### ISSUE TITLE
when will you release data processing code?

### ISSUE THREAD

**Issue by HaihuaQiu** [cszn/BSRGAN#5]
Hi, You did a good job！
I want to study the specific process, please tell me when you will release data processing code.
Thank you.

**Comment by jcai20** [comment]
BTW, which lib do you used for image processing? OpenCV? Thanks.

**Comment by HaihuaQiu** [comment]
> BTW, which lib do you used for image processing? OpenCV? Thanks.

Such as: Processed camera sensor noise NS,  anisotropic Gaussian kernels in your degradation model

**Comment by cszn** [comment]
@jcai20 @HaihuaQiu `cv2`, `scipy`, `numpy`, `torch`

**Comment by HaihuaQiu** [comment]
> @jcai20 @HaihuaQiu `cv2`, `scipy`, `numpy`, `torch`

I mean the degenerate model, can you tell me when to release code?

**Comment by cszn** [comment]
I use `cv2`, `scipy`, `numpy`, `torch` in my new degradation model. See also https://github.com/cszn/BSRGAN/issues/3
