### ISSUE TITLE
Can you share 2x model in another form? 

### ISSUE THREAD

**Issue by FlowDownTheRiver** [cszn/BSRGAN#6]
Is it possible for you to post the 2x pretrained model in the architecture of your 4x model? Other than that thanks for this great work. Are you thinking about improving the face restoration quality in later projects? 

Also I was wondering if you have any experimental models you would like to share for bsrgan without any denoising but with the ability of face restoration,motion blur removal etc? I mean bsrgan model but just without denoise

**Comment by cszn** [comment]
You can find the BSRGANx2 model now.
