### ISSUE TITLE
when use your degrade algorithm ，I get some  images  like this ，I wanna konw if it is correct？

### ISSUE THREAD

**Issue by erjihaoshi** [cszn/BSRGAN#7]
![00017](https://user-images.githubusercontent.com/37402962/116529535-a901c080-a90f-11eb-95f5-7cfc83321084.png)

**Comment by cszn** [comment]
Add some `img = np.clip(img, 0.0, 1.0)`

**Comment by erjihaoshi** [comment]
I add
    img = img/255.0
    img = np.clip(img,0.0,1.0)      at the end of function  degradation_pipeline(img): 
but still get  this  problem， 100 images test, about 10 image occur
i wanna konw when you test , did this situation happen?

**Comment by jeejeeli** [comment]
I have encountered this problem too, you can try that add  img=np.clip(img, 0.0,255) before doing JEPG compression.

**Comment by erjihaoshi** [comment]
thanks bro，it   did fix my problem， that is awsome，you are a angel.@jeejeeli

**Comment by FlowDownTheRiver** [comment]
Where is the degradation code guys and commandlines to use it? Can you put me in the right direction?
